int32 ID_R_SHOULDER_PITCH      =1
int32 ID_L_SHOULDER_PITCH      =2
int32 ID_R_SHOULDER_ROLL       =3
int32 ID_L_SHOULDER_ROLL       =4
int32 ID_R_ELBOW               =5
int32 ID_L_ELBOW               =6
int32 ID_R_HIP_YAW             =7
int32 ID_L_HIP_YAW             =8
int32 ID_R_HIP_ROLL            =9
int32 ID_L_HIP_ROLL            =10
int32 ID_R_HIP_PITCH           =11
int32 ID_L_HIP_PITCH           =12
int32 ID_R_KNEE                =13
int32 ID_L_KNEE                =14
int32 ID_R_ANKLE_PITCH         =15
int32 ID_L_ANKLE_PITCH         =16
int32 ID_R_ANKLE_ROLL          =17
int32 ID_L_ANKLE_ROLL          =18
int32 ID_HEAD_PAN              =19
int32 ID_HEAD_TILT             =20
int32 ID_R_ELBOW_YAW           =21
int32 ID_L_ELBOW_YAW           =22
int32 ID_R_WRIST_YAW           =23
int32 ID_L_WRIST_YAW           =24
int32 ID_R_GRIPPER             =25
int32 ID_L_GRIPPER             =26
int32 ID_HEAD_TILT_2           =27



int32 servos
float64[] positions
