/* Auto-generated by genmsg_cpp for file /home/sophie/catkin_ws/src/jimmy/msg/jimmy_servo.msg */
#ifndef JIMMY_MESSAGE_JIMMY_SERVO_H
#define JIMMY_MESSAGE_JIMMY_SERVO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace jimmy
{
template <class ContainerAllocator>
struct jimmy_servo_ {
  typedef jimmy_servo_<ContainerAllocator> Type;

  jimmy_servo_()
  : servo_numbers()
  , positions()
  {
  }

  jimmy_servo_(const ContainerAllocator& _alloc)
  : servo_numbers(_alloc)
  , positions(_alloc)
  {
  }

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _servo_numbers_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  servo_numbers;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _positions_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  positions;

  enum { ID_R_SHOULDER_PITCH = 16 };
  enum { ID_L_SHOULDER_PITCH = 12 };
  enum { ID_R_SHOULDER_ROLL = 17 };
  enum { ID_L_SHOULDER_ROLL = 13 };
  enum { ID_R_ELBOW = 19 };
  enum { ID_L_ELBOW = 15 };
  enum { ID_R_HIP_YAW = 6 };
  enum { ID_L_HIP_YAW = 0 };
  enum { ID_R_HIP_ROLL = 8 };
  enum { ID_L_HIP_ROLL = 2 };
  enum { ID_R_HIP_PITCH = 7 };
  enum { ID_L_HIP_PITCH = 1 };
  enum { ID_R_KNEE = 9 };
  enum { ID_L_KNEE = 3 };
  enum { ID_R_ANKLE_PITCH = 10 };
  enum { ID_L_ANKLE_PITCH = 4 };
  enum { ID_R_ANKLE_ROLL = 11 };
  enum { ID_L_ANKLE_ROLL = 5 };
  enum { ID_HEAD_PAN = 20 };
  enum { ID_HEAD_TILT = 21 };
  enum { ID_R_ELBOW_YAW = 18 };
  enum { ID_L_ELBOW_YAW = 14 };
  enum { ID_R_WRIST_YAW = 23 };
  enum { ID_L_WRIST_YAW = 24 };
  enum { ID_R_GRIPPER = 25 };
  enum { ID_L_GRIPPER = 26 };
  enum { ID_HEAD_TILT_2 = 22 };

  typedef boost::shared_ptr< ::jimmy::jimmy_servo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jimmy::jimmy_servo_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct jimmy_servo
typedef  ::jimmy::jimmy_servo_<std::allocator<void> > jimmy_servo;

typedef boost::shared_ptr< ::jimmy::jimmy_servo> jimmy_servoPtr;
typedef boost::shared_ptr< ::jimmy::jimmy_servo const> jimmy_servoConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::jimmy::jimmy_servo_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::jimmy::jimmy_servo_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace jimmy

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::jimmy::jimmy_servo_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::jimmy::jimmy_servo_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::jimmy::jimmy_servo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a12069c278d2ca26c24908f496f4482f";
  }

  static const char* value(const  ::jimmy::jimmy_servo_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa12069c278d2ca26ULL;
  static const uint64_t static_value2 = 0xc24908f496f4482fULL;
};

template<class ContainerAllocator>
struct DataType< ::jimmy::jimmy_servo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "jimmy/jimmy_servo";
  }

  static const char* value(const  ::jimmy::jimmy_servo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::jimmy::jimmy_servo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 ID_R_SHOULDER_PITCH      = 16\n\
int32 ID_L_SHOULDER_PITCH      = 12\n\
int32 ID_R_SHOULDER_ROLL       = 17\n\
int32 ID_L_SHOULDER_ROLL       = 13\n\
int32 ID_R_ELBOW               = 19\n\
int32 ID_L_ELBOW               = 15\n\
int32 ID_R_HIP_YAW             = 6\n\
int32 ID_L_HIP_YAW             = 0\n\
int32 ID_R_HIP_ROLL            = 8\n\
int32 ID_L_HIP_ROLL            = 2\n\
int32 ID_R_HIP_PITCH           = 7\n\
int32 ID_L_HIP_PITCH           = 1\n\
int32 ID_R_KNEE                = 9\n\
int32 ID_L_KNEE                = 3\n\
int32 ID_R_ANKLE_PITCH         = 10\n\
int32 ID_L_ANKLE_PITCH         = 4\n\
int32 ID_R_ANKLE_ROLL          = 11\n\
int32 ID_L_ANKLE_ROLL          = 5\n\
int32 ID_HEAD_PAN              = 20\n\
int32 ID_HEAD_TILT             = 21\n\
int32 ID_R_ELBOW_YAW           = 18\n\
int32 ID_L_ELBOW_YAW           = 14\n\
int32 ID_R_WRIST_YAW           = 23\n\
int32 ID_L_WRIST_YAW           = 24\n\
int32 ID_R_GRIPPER             = 25\n\
int32 ID_L_GRIPPER             = 26\n\
int32 ID_HEAD_TILT_2           = 22\n\
\n\
int32[] servo_numbers\n\
float64[] positions\n\
";
  }

  static const char* value(const  ::jimmy::jimmy_servo_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::jimmy::jimmy_servo_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.servo_numbers);
    stream.next(m.positions);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct jimmy_servo_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jimmy::jimmy_servo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::jimmy::jimmy_servo_<ContainerAllocator> & v) 
  {
    s << indent << "servo_numbers[]" << std::endl;
    for (size_t i = 0; i < v.servo_numbers.size(); ++i)
    {
      s << indent << "  servo_numbers[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.servo_numbers[i]);
    }
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.positions[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // JIMMY_MESSAGE_JIMMY_SERVO_H

